apiVersion: v1
kind: Service
metadata:
  labels:
    app: thbernar
    app.kubernetes.io/instance: thbernar-app
  name: thbernar-service
  namespace: dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: thbernar
  type: ClusterIP
