apiVersion: v1
kind: Service
metadata:
  labels:
    app: thbernar
  name: thbernar-service
  namespace: dev
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: thbernar
  type: ClusterIP
